# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: build-cachelib-rockylinux
on:
#   push:
  pull_request:
  # schedule:
  #    - cron:  '0 15 * * 2,4,6'
  #    - cron:  '0 17 * * *'
  workflow_dispatch:
jobs:
  build-cachelib-rockylinux:
    strategy:
      fail-fast: false
      matrix:
        version: ["8.6", "9.0"]
    name: "RockyLinux-${{matrix.version}} - Build CacheLib with all dependencies"
    runs-on: ubuntu-latest
    # Docker container image name
    container: "rockylinux:${{matrix.version}}"
    steps:
      - name: "Show Head Commit"
        env:
          CONTENT: ${{ toJSON(github.event.head_commit) }}
        run: echo "$CONTENT"
      - name: "update packages"
        # stock centos has a problem with CMAKE, fails with:
        #  "cmake: symbol lookup error: cmake: undefined symbol: archive_write_add_filter_zstd"
        # updating solves it
        run: dnf update -y
      - name: "install sudo,git"
        run: dnf install -y sudo git cmake gcc procps
      - name: "System Information"
        run: |
          echo === uname ===
          uname -a
          echo === /etc/os-release ===
          cat /etc/os-release
          echo === df -hl ===
          df -hl
          echo === nproc ===
          nproc || true
          echo === free -h ===
          free -h
          echo === top ===
          top -b -n1 -1 -Eg || timeout 1 top -b -n1
          echo === env ===
          env
          echo === gcc -v ===
          gcc -v
      - name: "checkout sources"
        uses: actions/checkout@v3
      - name: "Install Prerequisites"
        run: ./contrib/build.sh -S -B
      - name: "Test: update-submodules"
        run: ./contrib/update-submodules.sh
      - name: "Install dependency: zstd"
        run: ./contrib/build-package.sh -j -v -i zstd
      - name: "Install dependency: googleflags"
        run: ./contrib/build-package.sh -j -v -i googleflags
      - name: "Install dependency: googlelog"
        run: ./contrib/build-package.sh -j -v -i googlelog
      - name: "Install dependency: googletest"
        run: ./contrib/build-package.sh -j -v -i googletest
      - name: "Install dependency: sparsemap"
        run: ./contrib/build-package.sh -j -v -i sparsemap
      - name: "Install dependency: fmt"
        run: ./contrib/build-package.sh -j -v -i fmt
      - name: "Use cache for built libraries of submodules"
        uses: actions/cache@v3
        id: cache-submodules
        with:
          # Using HEAD of submodules
          key: ${{ github.job }}-${{matrix.version}}-build-${{ hashFiles('.git/modules/*/HEAD') }}
          path: |
            opt/cachelib/lib
            # opt/cachelib/lib/libfolly*
            # opt/cachelib/lib/libfizz*
            # opt/cachelib/lib/libwangle*
            opt/cachelib/include
            opt/cachelib/bin/thrift1
            opt/cachelib/bin/fizz
            opt/cachelib/bin/fizz-bogoshim
      - name: "Install dependency: folly (rockylinux-9.0)"
        run: |
          # see: https://aur.archlinux.org/packages/folly#comment-862543
          sed -i '$aset(LIBDWARF_INCLUDE_DIRS "/usr/include/libdwarf-0")' cachelib/external/folly/CMake/FindLibDwarf.cmake
          ./contrib/build-package.sh -S -j -v -i folly
        if: steps.cache-submodules.outputs.cache-hit != 'true' && matrix.version == '9.0'
        # libdwarf error if using cache - can't find /usr/include/libdwarf-0"
        # if:  matrix.version == '9.0'
      - name: "Install dependency: folly (rockylinux-8.0)"
        run: ./contrib/build-package.sh -j -v -i folly
        if: steps.cache-submodules.outputs.cache-hit != 'true' && matrix.version != '9.0'
      - name: "Install dependency: fizz"
        run: ./contrib/build-package.sh -j -v -i fizz
        if: steps.cache-submodules.outputs.cache-hit != 'true'
      - name: "Install dependency: wangle"
        run: ./contrib/build-package.sh -j -v -i wangle
        if: steps.cache-submodules.outputs.cache-hit != 'true'
      - name: "Install dependency: fbthrift"
        run: ./contrib/build-package.sh -j -v -i fbthrift
        if: steps.cache-submodules.outputs.cache-hit != 'true'
      - name: "build CacheLib"
        # Build cachelib in debug mode (-d) and with all tests (-t)
        run: ./contrib/build-package.sh -j -v -i -d -t cachelib
      - name: "Run tests"
        run: ./contrib/run_tests.sh
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cachelib-cmake-logs
          path: |
            build-cachelib/CMakeFiles/*.log
            build-cachelib/CMakeCache.txt
            build-cachelib/Makefile
            build-cachelib/**/Makefile
          if-no-files-found: warn
          retention-days: 1
      - uses: actions/upload-artifact@v3
        with:
          name: cachelib-tests
          path: opt/cachelib/tests/*.log
          if-no-files-found: warn
          retention-days: 7
